
ARDUINO_DIR=/home/cdupont/Documents/workspace/arduino-1.8.10/
BOARD_TAG    = pro
BOARD_SUB    = 8MHzatmega328 
MONITOR_PORT = /dev/ttyUSB0
USER_LIB_PATH = ../../libraries
ARDUINO_LIBS = SPI SX1272 LowPower EEPROM
MONITOR_CMD = cat
MONITOR_BAUDRATE = 38400 

include /usr/share/arduino/Arduino.mk

