#!/usr/bin/python3

from flask import Flask, request, jsonify
from flask_cors import CORS, cross_origin
from simple_rpc import Interface
import os
from threading import Thread

app = Flask(__name__)
app.config["DEBUG"] = True
cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'

wazidev_port = os.getenv("WAZIDEV_PORT", '/dev/ttyUSB0')
interface = Interface("/dev/ttyUSB0")


@app.route('/', methods=['POST'])
def postVal():
   print(request)
   return jsonify(sendValueWaziDev(int(request.json["val"])))


def sendValueWaziDev(val: int) -> str:
    print("sending value: " + str(val))
    return interface.sendLoRaWAN2(val).decode("utf-8")

app.run()

if __name__ == '__main__':
    print("main")
